// Code generated by go-swagger; DO NOT EDIT.

package misc

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "mingchuan.me/app/drivers/swagger/models"
)

// HealthCheckOKCode is the HTTP code returned for type HealthCheckOK
const HealthCheckOKCode int = 200

/*HealthCheckOK success

swagger:response healthCheckOK
*/
type HealthCheckOK struct {

	/*
	  In: Body
	*/
	Payload *models.HealthResponse `json:"body,omitempty"`
}

// NewHealthCheckOK creates HealthCheckOK with default headers values
func NewHealthCheckOK() *HealthCheckOK {

	return &HealthCheckOK{}
}

// WithPayload adds the payload to the health check o k response
func (o *HealthCheckOK) WithPayload(payload *models.HealthResponse) *HealthCheckOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the health check o k response
func (o *HealthCheckOK) SetPayload(payload *models.HealthResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *HealthCheckOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// HealthCheckBadRequestCode is the HTTP code returned for type HealthCheckBadRequest
const HealthCheckBadRequestCode int = 400

/*HealthCheckBadRequest service error

swagger:response healthCheckBadRequest
*/
type HealthCheckBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ServiceError `json:"body,omitempty"`
}

// NewHealthCheckBadRequest creates HealthCheckBadRequest with default headers values
func NewHealthCheckBadRequest() *HealthCheckBadRequest {

	return &HealthCheckBadRequest{}
}

// WithPayload adds the payload to the health check bad request response
func (o *HealthCheckBadRequest) WithPayload(payload *models.ServiceError) *HealthCheckBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the health check bad request response
func (o *HealthCheckBadRequest) SetPayload(payload *models.ServiceError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *HealthCheckBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// HealthCheckInternalServerErrorCode is the HTTP code returned for type HealthCheckInternalServerError
const HealthCheckInternalServerErrorCode int = 500

/*HealthCheckInternalServerError service error (fatal)

swagger:response healthCheckInternalServerError
*/
type HealthCheckInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ServiceError `json:"body,omitempty"`
}

// NewHealthCheckInternalServerError creates HealthCheckInternalServerError with default headers values
func NewHealthCheckInternalServerError() *HealthCheckInternalServerError {

	return &HealthCheckInternalServerError{}
}

// WithPayload adds the payload to the health check internal server error response
func (o *HealthCheckInternalServerError) WithPayload(payload *models.ServiceError) *HealthCheckInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the health check internal server error response
func (o *HealthCheckInternalServerError) SetPayload(payload *models.ServiceError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *HealthCheckInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
