// Code generated by go-swagger; DO NOT EDIT.

package todo

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// CreateItemTHandlerFunc turns a function with the right signature into a create item t handler
type CreateItemTHandlerFunc func(CreateItemTParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateItemTHandlerFunc) Handle(params CreateItemTParams) middleware.Responder {
	return fn(params)
}

// CreateItemTHandler interface for that can handle valid create item t params
type CreateItemTHandler interface {
	Handle(CreateItemTParams) middleware.Responder
}

// NewCreateItemT creates a new http.Handler for the create item t operation
func NewCreateItemT(ctx *middleware.Context, handler CreateItemTHandler) *CreateItemT {
	return &CreateItemT{Context: ctx, Handler: handler}
}

/*CreateItemT swagger:route POST /admin/todos todo createItemT

create TODO item

*/
type CreateItemT struct {
	Context *middleware.Context
	Handler CreateItemTHandler
}

func (o *CreateItemT) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCreateItemTParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
