// Code generated by go-swagger; DO NOT EDIT.

package todo

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "mingchuan.me/app/drivers/swagger/models"
)

// CreateItemTOKCode is the HTTP code returned for type CreateItemTOK
const CreateItemTOKCode int = 200

/*CreateItemTOK success

swagger:response createItemTOK
*/
type CreateItemTOK struct {

	/*
	  In: Body
	*/
	Payload *models.Todo `json:"body,omitempty"`
}

// NewCreateItemTOK creates CreateItemTOK with default headers values
func NewCreateItemTOK() *CreateItemTOK {

	return &CreateItemTOK{}
}

// WithPayload adds the payload to the create item t o k response
func (o *CreateItemTOK) WithPayload(payload *models.Todo) *CreateItemTOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create item t o k response
func (o *CreateItemTOK) SetPayload(payload *models.Todo) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateItemTOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateItemTBadRequestCode is the HTTP code returned for type CreateItemTBadRequest
const CreateItemTBadRequestCode int = 400

/*CreateItemTBadRequest service error

swagger:response createItemTBadRequest
*/
type CreateItemTBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ServiceError `json:"body,omitempty"`
}

// NewCreateItemTBadRequest creates CreateItemTBadRequest with default headers values
func NewCreateItemTBadRequest() *CreateItemTBadRequest {

	return &CreateItemTBadRequest{}
}

// WithPayload adds the payload to the create item t bad request response
func (o *CreateItemTBadRequest) WithPayload(payload *models.ServiceError) *CreateItemTBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create item t bad request response
func (o *CreateItemTBadRequest) SetPayload(payload *models.ServiceError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateItemTBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateItemTInternalServerErrorCode is the HTTP code returned for type CreateItemTInternalServerError
const CreateItemTInternalServerErrorCode int = 500

/*CreateItemTInternalServerError service error (fatal)

swagger:response createItemTInternalServerError
*/
type CreateItemTInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ServiceError `json:"body,omitempty"`
}

// NewCreateItemTInternalServerError creates CreateItemTInternalServerError with default headers values
func NewCreateItemTInternalServerError() *CreateItemTInternalServerError {

	return &CreateItemTInternalServerError{}
}

// WithPayload adds the payload to the create item t internal server error response
func (o *CreateItemTInternalServerError) WithPayload(payload *models.ServiceError) *CreateItemTInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create item t internal server error response
func (o *CreateItemTInternalServerError) SetPayload(payload *models.ServiceError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateItemTInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
