// Code generated by go-swagger; DO NOT EDIT.

package todo

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DeleteItemTHandlerFunc turns a function with the right signature into a delete item t handler
type DeleteItemTHandlerFunc func(DeleteItemTParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteItemTHandlerFunc) Handle(params DeleteItemTParams) middleware.Responder {
	return fn(params)
}

// DeleteItemTHandler interface for that can handle valid delete item t params
type DeleteItemTHandler interface {
	Handle(DeleteItemTParams) middleware.Responder
}

// NewDeleteItemT creates a new http.Handler for the delete item t operation
func NewDeleteItemT(ctx *middleware.Context, handler DeleteItemTHandler) *DeleteItemT {
	return &DeleteItemT{Context: ctx, Handler: handler}
}

/*DeleteItemT swagger:route DELETE /admin/todos/{id} todo deleteItemT

delete TODO item

*/
type DeleteItemT struct {
	Context *middleware.Context
	Handler DeleteItemTHandler
}

func (o *DeleteItemT) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteItemTParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
