// Code generated by go-swagger; DO NOT EDIT.

package todo

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "mingchuan.me/app/drivers/swagger/models"
)

// ListAllItemsTOKCode is the HTTP code returned for type ListAllItemsTOK
const ListAllItemsTOKCode int = 200

/*ListAllItemsTOK success

swagger:response listAllItemsTOK
*/
type ListAllItemsTOK struct {

	/*
	  In: Body
	*/
	Payload *models.TodoList `json:"body,omitempty"`
}

// NewListAllItemsTOK creates ListAllItemsTOK with default headers values
func NewListAllItemsTOK() *ListAllItemsTOK {

	return &ListAllItemsTOK{}
}

// WithPayload adds the payload to the list all items t o k response
func (o *ListAllItemsTOK) WithPayload(payload *models.TodoList) *ListAllItemsTOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list all items t o k response
func (o *ListAllItemsTOK) SetPayload(payload *models.TodoList) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListAllItemsTOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListAllItemsTBadRequestCode is the HTTP code returned for type ListAllItemsTBadRequest
const ListAllItemsTBadRequestCode int = 400

/*ListAllItemsTBadRequest service error

swagger:response listAllItemsTBadRequest
*/
type ListAllItemsTBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ServiceError `json:"body,omitempty"`
}

// NewListAllItemsTBadRequest creates ListAllItemsTBadRequest with default headers values
func NewListAllItemsTBadRequest() *ListAllItemsTBadRequest {

	return &ListAllItemsTBadRequest{}
}

// WithPayload adds the payload to the list all items t bad request response
func (o *ListAllItemsTBadRequest) WithPayload(payload *models.ServiceError) *ListAllItemsTBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list all items t bad request response
func (o *ListAllItemsTBadRequest) SetPayload(payload *models.ServiceError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListAllItemsTBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListAllItemsTInternalServerErrorCode is the HTTP code returned for type ListAllItemsTInternalServerError
const ListAllItemsTInternalServerErrorCode int = 500

/*ListAllItemsTInternalServerError service error (fatal)

swagger:response listAllItemsTInternalServerError
*/
type ListAllItemsTInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ServiceError `json:"body,omitempty"`
}

// NewListAllItemsTInternalServerError creates ListAllItemsTInternalServerError with default headers values
func NewListAllItemsTInternalServerError() *ListAllItemsTInternalServerError {

	return &ListAllItemsTInternalServerError{}
}

// WithPayload adds the payload to the list all items t internal server error response
func (o *ListAllItemsTInternalServerError) WithPayload(payload *models.ServiceError) *ListAllItemsTInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list all items t internal server error response
func (o *ListAllItemsTInternalServerError) SetPayload(payload *models.ServiceError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListAllItemsTInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
