// Code generated by go-swagger; DO NOT EDIT.

package blog

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "mingchuan.me/app/drivers/swagger/models"
)

// CreatePostOKCode is the HTTP code returned for type CreatePostOK
const CreatePostOKCode int = 200

/*CreatePostOK success

swagger:response createPostOK
*/
type CreatePostOK struct {

	/*
	  In: Body
	*/
	Payload *models.Post `json:"body,omitempty"`
}

// NewCreatePostOK creates CreatePostOK with default headers values
func NewCreatePostOK() *CreatePostOK {

	return &CreatePostOK{}
}

// WithPayload adds the payload to the create post o k response
func (o *CreatePostOK) WithPayload(payload *models.Post) *CreatePostOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create post o k response
func (o *CreatePostOK) SetPayload(payload *models.Post) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreatePostOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreatePostBadRequestCode is the HTTP code returned for type CreatePostBadRequest
const CreatePostBadRequestCode int = 400

/*CreatePostBadRequest service error

swagger:response createPostBadRequest
*/
type CreatePostBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ServiceError `json:"body,omitempty"`
}

// NewCreatePostBadRequest creates CreatePostBadRequest with default headers values
func NewCreatePostBadRequest() *CreatePostBadRequest {

	return &CreatePostBadRequest{}
}

// WithPayload adds the payload to the create post bad request response
func (o *CreatePostBadRequest) WithPayload(payload *models.ServiceError) *CreatePostBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create post bad request response
func (o *CreatePostBadRequest) SetPayload(payload *models.ServiceError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreatePostBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreatePostInternalServerErrorCode is the HTTP code returned for type CreatePostInternalServerError
const CreatePostInternalServerErrorCode int = 500

/*CreatePostInternalServerError service error (fatal)

swagger:response createPostInternalServerError
*/
type CreatePostInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ServiceError `json:"body,omitempty"`
}

// NewCreatePostInternalServerError creates CreatePostInternalServerError with default headers values
func NewCreatePostInternalServerError() *CreatePostInternalServerError {

	return &CreatePostInternalServerError{}
}

// WithPayload adds the payload to the create post internal server error response
func (o *CreatePostInternalServerError) WithPayload(payload *models.ServiceError) *CreatePostInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create post internal server error response
func (o *CreatePostInternalServerError) SetPayload(payload *models.ServiceError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreatePostInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
