// Code generated by go-swagger; DO NOT EDIT.

package blog

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "mingchuan.me/app/drivers/swagger/models"
)

// DeletePostOKCode is the HTTP code returned for type DeletePostOK
const DeletePostOKCode int = 200

/*DeletePostOK success

swagger:response deletePostOK
*/
type DeletePostOK struct {

	/*
	  In: Body
	*/
	Payload *models.DeletePostResponse `json:"body,omitempty"`
}

// NewDeletePostOK creates DeletePostOK with default headers values
func NewDeletePostOK() *DeletePostOK {

	return &DeletePostOK{}
}

// WithPayload adds the payload to the delete post o k response
func (o *DeletePostOK) WithPayload(payload *models.DeletePostResponse) *DeletePostOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete post o k response
func (o *DeletePostOK) SetPayload(payload *models.DeletePostResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeletePostOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeletePostBadRequestCode is the HTTP code returned for type DeletePostBadRequest
const DeletePostBadRequestCode int = 400

/*DeletePostBadRequest service error

swagger:response deletePostBadRequest
*/
type DeletePostBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ServiceError `json:"body,omitempty"`
}

// NewDeletePostBadRequest creates DeletePostBadRequest with default headers values
func NewDeletePostBadRequest() *DeletePostBadRequest {

	return &DeletePostBadRequest{}
}

// WithPayload adds the payload to the delete post bad request response
func (o *DeletePostBadRequest) WithPayload(payload *models.ServiceError) *DeletePostBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete post bad request response
func (o *DeletePostBadRequest) SetPayload(payload *models.ServiceError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeletePostBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeletePostInternalServerErrorCode is the HTTP code returned for type DeletePostInternalServerError
const DeletePostInternalServerErrorCode int = 500

/*DeletePostInternalServerError service error (fatal)

swagger:response deletePostInternalServerError
*/
type DeletePostInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ServiceError `json:"body,omitempty"`
}

// NewDeletePostInternalServerError creates DeletePostInternalServerError with default headers values
func NewDeletePostInternalServerError() *DeletePostInternalServerError {

	return &DeletePostInternalServerError{}
}

// WithPayload adds the payload to the delete post internal server error response
func (o *DeletePostInternalServerError) WithPayload(payload *models.ServiceError) *DeletePostInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete post internal server error response
func (o *DeletePostInternalServerError) SetPayload(payload *models.ServiceError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeletePostInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
