// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// DeletePostResponse delete post response
// swagger:model DeletePostResponse
type DeletePostResponse struct {

	// delete post id
	ID int64 `json:"id,omitempty"`

	// success
	Success bool `json:"success,omitempty"`
}

// Validate validates this delete post response
func (m *DeletePostResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DeletePostResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DeletePostResponse) UnmarshalBinary(b []byte) error {
	var res DeletePostResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
