// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// JwtResponse jwt response
// swagger:model JwtResponse
type JwtResponse struct {

	// JWT secret for authorization.
	// Required: true
	Jwt *string `json:"jwt"`
}

// Validate validates this jwt response
func (m *JwtResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateJwt(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *JwtResponse) validateJwt(formats strfmt.Registry) error {

	if err := validate.Required("jwt", "body", m.Jwt); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *JwtResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *JwtResponse) UnmarshalBinary(b []byte) error {
	var res JwtResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
