// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// PostsList posts list
// swagger:model PostsList
type PostsList struct {

	// cursor
	Cursor string `json:"cursor,omitempty"`

	// has more
	HasMore bool `json:"hasMore,omitempty"`

	// posts
	Posts []*Post `json:"posts"`
}

// Validate validates this posts list
func (m *PostsList) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePosts(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PostsList) validatePosts(formats strfmt.Registry) error {

	if swag.IsZero(m.Posts) { // not required
		return nil
	}

	for i := 0; i < len(m.Posts); i++ {
		if swag.IsZero(m.Posts[i]) { // not required
			continue
		}

		if m.Posts[i] != nil {
			if err := m.Posts[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("posts" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *PostsList) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostsList) UnmarshalBinary(b []byte) error {
	var res PostsList
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
