// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TodoList todo list
// swagger:model TodoList
type TodoList struct {

	// todos
	Todos []*Todo `json:"todos"`
}

// Validate validates this todo list
func (m *TodoList) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTodos(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TodoList) validateTodos(formats strfmt.Registry) error {

	if swag.IsZero(m.Todos) { // not required
		return nil
	}

	for i := 0; i < len(m.Todos); i++ {
		if swag.IsZero(m.Todos[i]) { // not required
			continue
		}

		if m.Todos[i] != nil {
			if err := m.Todos[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("todos" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *TodoList) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TodoList) UnmarshalBinary(b []byte) error {
	var res TodoList
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
