services:
  - docker

git:
  depth: 1

notifications:
  email: true

script:
  - docker-compose build mce_site mce_api
  - MCE_ENV=build docker-compose up mce_site mce_api

before_deploy:
  - cd $TRAVIS_BUILD_DIR
  - tar -cvzf build.tar.gz build
