language: generic

services:
  - docker
git:
  depth: 1
notifications:
  email: true

env:
  - MCE_ENV=build

addons:
  ssh_known_hosts:
    - mingchuan.me

script:
  - docker-compose build mce_site mce_api
  - docker-compose run mce_api bash /app/build.sh
  - docker-compose run mce_site bash /app/build.sh

before_deploy:
  - openssl aes-256-cbc -K $encrypted_b30053e1ddd1_key -iv $encrypted_b30053e1ddd1_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  # tar artifacts
  - cd $TRAVIS_BUILD_DIR
  - tar -cvzf build.tar.gz build

deploy:
  provider: script
  skip_cleanup: true
  script: scp $TRAVIS_BUILD_DIR/build.tar.gz root@mingchuan.me:/srv/mingchuan.me
  on:
    branch: master