version: '3.4'

services:
  mce:
    build:
      context: .
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      MCE_ENV: ${MCE_ENV}
      DEBUG: ${DEBUG}
      HOST: '0.0.0.0'
      SITE_BASE_URL: ${SITE_BASE_URL}
    depends_on:
      - db
    volumes:
      # config
      - ./config:/srv/config
      - ./storage/caddy:/root/.caddy
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306"
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}      
volumes:  
  db_data:
