version: "3.2"
services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=general-user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=mce_main
    ports:
      - target: 3306
        published: 3306
        mode: host
    volumes:
      - "./docker-setup:/docker-entrypoint-initdb.d"
  mce:
    image: demohn/mingchuan.me:1
    env_file:
      - .env
    ports:
      - target: 8080
        published: 8080
        mode: host
    volumes:
      - "./Caddyfile:/etc/Caddyfile"
    depends_on:
      - mysql
      
