// Code generated by go-swagger; DO NOT EDIT.

package todo

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "mingchuan.me/api/models"
)

// DeleteItemTOKCode is the HTTP code returned for type DeleteItemTOK
const DeleteItemTOKCode int = 200

/*DeleteItemTOK success

swagger:response deleteItemTOK
*/
type DeleteItemTOK struct {

	/*
	  In: Body
	*/
	Payload *models.Todo `json:"body,omitempty"`
}

// NewDeleteItemTOK creates DeleteItemTOK with default headers values
func NewDeleteItemTOK() *DeleteItemTOK {

	return &DeleteItemTOK{}
}

// WithPayload adds the payload to the delete item t o k response
func (o *DeleteItemTOK) WithPayload(payload *models.Todo) *DeleteItemTOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete item t o k response
func (o *DeleteItemTOK) SetPayload(payload *models.Todo) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteItemTOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteItemTBadRequestCode is the HTTP code returned for type DeleteItemTBadRequest
const DeleteItemTBadRequestCode int = 400

/*DeleteItemTBadRequest service error

swagger:response deleteItemTBadRequest
*/
type DeleteItemTBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ServiceError `json:"body,omitempty"`
}

// NewDeleteItemTBadRequest creates DeleteItemTBadRequest with default headers values
func NewDeleteItemTBadRequest() *DeleteItemTBadRequest {

	return &DeleteItemTBadRequest{}
}

// WithPayload adds the payload to the delete item t bad request response
func (o *DeleteItemTBadRequest) WithPayload(payload *models.ServiceError) *DeleteItemTBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete item t bad request response
func (o *DeleteItemTBadRequest) SetPayload(payload *models.ServiceError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteItemTBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteItemTInternalServerErrorCode is the HTTP code returned for type DeleteItemTInternalServerError
const DeleteItemTInternalServerErrorCode int = 500

/*DeleteItemTInternalServerError service error (fatal)

swagger:response deleteItemTInternalServerError
*/
type DeleteItemTInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ServiceError `json:"body,omitempty"`
}

// NewDeleteItemTInternalServerError creates DeleteItemTInternalServerError with default headers values
func NewDeleteItemTInternalServerError() *DeleteItemTInternalServerError {

	return &DeleteItemTInternalServerError{}
}

// WithPayload adds the payload to the delete item t internal server error response
func (o *DeleteItemTInternalServerError) WithPayload(payload *models.ServiceError) *DeleteItemTInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete item t internal server error response
func (o *DeleteItemTInternalServerError) SetPayload(payload *models.ServiceError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteItemTInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
