// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// UpdatePostPayload update post payload
// swagger:model UpdatePostPayload
type UpdatePostPayload struct {

	// content
	Content *string `json:"content,omitempty"`

	// permission
	// Enum: [PUBLIC PRIVATE]
	Permission *string `json:"permission,omitempty"`

	// status
	// Enum: [PUBLISHED DRAFTED REMOVED]
	Status *string `json:"status,omitempty"`

	// title
	Title *string `json:"title,omitempty"`
}

// Validate validates this update post payload
func (m *UpdatePostPayload) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePermission(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var updatePostPayloadTypePermissionPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["PUBLIC","PRIVATE"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		updatePostPayloadTypePermissionPropEnum = append(updatePostPayloadTypePermissionPropEnum, v)
	}
}

const (

	// UpdatePostPayloadPermissionPUBLIC captures enum value "PUBLIC"
	UpdatePostPayloadPermissionPUBLIC string = "PUBLIC"

	// UpdatePostPayloadPermissionPRIVATE captures enum value "PRIVATE"
	UpdatePostPayloadPermissionPRIVATE string = "PRIVATE"
)

// prop value enum
func (m *UpdatePostPayload) validatePermissionEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, updatePostPayloadTypePermissionPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *UpdatePostPayload) validatePermission(formats strfmt.Registry) error {

	if swag.IsZero(m.Permission) { // not required
		return nil
	}

	// value enum
	if err := m.validatePermissionEnum("permission", "body", *m.Permission); err != nil {
		return err
	}

	return nil
}

var updatePostPayloadTypeStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["PUBLISHED","DRAFTED","REMOVED"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		updatePostPayloadTypeStatusPropEnum = append(updatePostPayloadTypeStatusPropEnum, v)
	}
}

const (

	// UpdatePostPayloadStatusPUBLISHED captures enum value "PUBLISHED"
	UpdatePostPayloadStatusPUBLISHED string = "PUBLISHED"

	// UpdatePostPayloadStatusDRAFTED captures enum value "DRAFTED"
	UpdatePostPayloadStatusDRAFTED string = "DRAFTED"

	// UpdatePostPayloadStatusREMOVED captures enum value "REMOVED"
	UpdatePostPayloadStatusREMOVED string = "REMOVED"
)

// prop value enum
func (m *UpdatePostPayload) validateStatusEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, updatePostPayloadTypeStatusPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *UpdatePostPayload) validateStatus(formats strfmt.Registry) error {

	if swag.IsZero(m.Status) { // not required
		return nil
	}

	// value enum
	if err := m.validateStatusEnum("status", "body", *m.Status); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *UpdatePostPayload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdatePostPayload) UnmarshalBinary(b []byte) error {
	var res UpdatePostPayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
