// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi mingchuan.me API
This doc contains all APIs for https://mingchuan.me.


    Schemes:
      http
    Host: localhost:4000
    BasePath: /api/v1
    Version: 1.0.0
    Contact: <demohn2016@gmail.com>

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
