// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "mingchuan.me/app/drivers/swagger/models"
)

// RegisterAdminOKCode is the HTTP code returned for type RegisterAdminOK
const RegisterAdminOKCode int = 200

/*RegisterAdminOK success

swagger:response registerAdminOK
*/
type RegisterAdminOK struct {

	/*
	  In: Body
	*/
	Payload *models.JwtResponse `json:"body,omitempty"`
}

// NewRegisterAdminOK creates RegisterAdminOK with default headers values
func NewRegisterAdminOK() *RegisterAdminOK {

	return &RegisterAdminOK{}
}

// WithPayload adds the payload to the register admin o k response
func (o *RegisterAdminOK) WithPayload(payload *models.JwtResponse) *RegisterAdminOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the register admin o k response
func (o *RegisterAdminOK) SetPayload(payload *models.JwtResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RegisterAdminOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RegisterAdminBadRequestCode is the HTTP code returned for type RegisterAdminBadRequest
const RegisterAdminBadRequestCode int = 400

/*RegisterAdminBadRequest service error

swagger:response registerAdminBadRequest
*/
type RegisterAdminBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ServiceError `json:"body,omitempty"`
}

// NewRegisterAdminBadRequest creates RegisterAdminBadRequest with default headers values
func NewRegisterAdminBadRequest() *RegisterAdminBadRequest {

	return &RegisterAdminBadRequest{}
}

// WithPayload adds the payload to the register admin bad request response
func (o *RegisterAdminBadRequest) WithPayload(payload *models.ServiceError) *RegisterAdminBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the register admin bad request response
func (o *RegisterAdminBadRequest) SetPayload(payload *models.ServiceError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RegisterAdminBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RegisterAdminInternalServerErrorCode is the HTTP code returned for type RegisterAdminInternalServerError
const RegisterAdminInternalServerErrorCode int = 500

/*RegisterAdminInternalServerError service error (fatal)

swagger:response registerAdminInternalServerError
*/
type RegisterAdminInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ServiceError `json:"body,omitempty"`
}

// NewRegisterAdminInternalServerError creates RegisterAdminInternalServerError with default headers values
func NewRegisterAdminInternalServerError() *RegisterAdminInternalServerError {

	return &RegisterAdminInternalServerError{}
}

// WithPayload adds the payload to the register admin internal server error response
func (o *RegisterAdminInternalServerError) WithPayload(payload *models.ServiceError) *RegisterAdminInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the register admin internal server error response
func (o *RegisterAdminInternalServerError) SetPayload(payload *models.ServiceError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RegisterAdminInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
