// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// RegisterAdminHandlerFunc turns a function with the right signature into a register admin handler
type RegisterAdminHandlerFunc func(RegisterAdminParams) middleware.Responder

// Handle executing the request and returning a response
func (fn RegisterAdminHandlerFunc) Handle(params RegisterAdminParams) middleware.Responder {
	return fn(params)
}

// RegisterAdminHandler interface for that can handle valid register admin params
type RegisterAdminHandler interface {
	Handle(RegisterAdminParams) middleware.Responder
}

// NewRegisterAdmin creates a new http.Handler for the register admin operation
func NewRegisterAdmin(ctx *middleware.Context, handler RegisterAdminHandler) *RegisterAdmin {
	return &RegisterAdmin{Context: ctx, Handler: handler}
}

/*RegisterAdmin swagger:route POST /accounts/register-admin account registerAdmin

Register a new admin account.

*/
type RegisterAdmin struct {
	Context *middleware.Context
	Handler RegisterAdminHandler
}

func (o *RegisterAdmin) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewRegisterAdminParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
