// Code generated by go-swagger; DO NOT EDIT.

package blog

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetOnePublicPostHandlerFunc turns a function with the right signature into a get one public post handler
type GetOnePublicPostHandlerFunc func(GetOnePublicPostParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetOnePublicPostHandlerFunc) Handle(params GetOnePublicPostParams) middleware.Responder {
	return fn(params)
}

// GetOnePublicPostHandler interface for that can handle valid get one public post params
type GetOnePublicPostHandler interface {
	Handle(GetOnePublicPostParams) middleware.Responder
}

// NewGetOnePublicPost creates a new http.Handler for the get one public post operation
func NewGetOnePublicPost(ctx *middleware.Context, handler GetOnePublicPostHandler) *GetOnePublicPost {
	return &GetOnePublicPost{Context: ctx, Handler: handler}
}

/*GetOnePublicPost swagger:route GET /posts/{id} blog getOnePublicPost

get one **public** post

*/
type GetOnePublicPost struct {
	Context *middleware.Context
	Handler GetOnePublicPostHandler
}

func (o *GetOnePublicPost) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetOnePublicPostParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
