// Code generated by go-swagger; DO NOT EDIT.

package blog

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetOnePostHandlerFunc turns a function with the right signature into a get one post handler
type GetOnePostHandlerFunc func(GetOnePostParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetOnePostHandlerFunc) Handle(params GetOnePostParams) middleware.Responder {
	return fn(params)
}

// GetOnePostHandler interface for that can handle valid get one post params
type GetOnePostHandler interface {
	Handle(GetOnePostParams) middleware.Responder
}

// NewGetOnePost creates a new http.Handler for the get one post operation
func NewGetOnePost(ctx *middleware.Context, handler GetOnePostHandler) *GetOnePost {
	return &GetOnePost{Context: ctx, Handler: handler}
}

/*GetOnePost swagger:route GET /admin/posts/{id} blog getOnePost

get one post (all)

*/
type GetOnePost struct {
	Context *middleware.Context
	Handler GetOnePostHandler
}

func (o *GetOnePost) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetOnePostParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
