// Code generated by go-swagger; DO NOT EDIT.

package blog

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "mingchuan.me/api/models"
)

// GetOnePostOKCode is the HTTP code returned for type GetOnePostOK
const GetOnePostOKCode int = 200

/*GetOnePostOK success

swagger:response getOnePostOK
*/
type GetOnePostOK struct {

	/*
	  In: Body
	*/
	Payload *models.Post `json:"body,omitempty"`
}

// NewGetOnePostOK creates GetOnePostOK with default headers values
func NewGetOnePostOK() *GetOnePostOK {

	return &GetOnePostOK{}
}

// WithPayload adds the payload to the get one post o k response
func (o *GetOnePostOK) WithPayload(payload *models.Post) *GetOnePostOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get one post o k response
func (o *GetOnePostOK) SetPayload(payload *models.Post) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetOnePostOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetOnePostBadRequestCode is the HTTP code returned for type GetOnePostBadRequest
const GetOnePostBadRequestCode int = 400

/*GetOnePostBadRequest service error

swagger:response getOnePostBadRequest
*/
type GetOnePostBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ServiceError `json:"body,omitempty"`
}

// NewGetOnePostBadRequest creates GetOnePostBadRequest with default headers values
func NewGetOnePostBadRequest() *GetOnePostBadRequest {

	return &GetOnePostBadRequest{}
}

// WithPayload adds the payload to the get one post bad request response
func (o *GetOnePostBadRequest) WithPayload(payload *models.ServiceError) *GetOnePostBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get one post bad request response
func (o *GetOnePostBadRequest) SetPayload(payload *models.ServiceError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetOnePostBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetOnePostInternalServerErrorCode is the HTTP code returned for type GetOnePostInternalServerError
const GetOnePostInternalServerErrorCode int = 500

/*GetOnePostInternalServerError service error (fatal)

swagger:response getOnePostInternalServerError
*/
type GetOnePostInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ServiceError `json:"body,omitempty"`
}

// NewGetOnePostInternalServerError creates GetOnePostInternalServerError with default headers values
func NewGetOnePostInternalServerError() *GetOnePostInternalServerError {

	return &GetOnePostInternalServerError{}
}

// WithPayload adds the payload to the get one post internal server error response
func (o *GetOnePostInternalServerError) WithPayload(payload *models.ServiceError) *GetOnePostInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get one post internal server error response
func (o *GetOnePostInternalServerError) SetPayload(payload *models.ServiceError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetOnePostInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
