// Code generated by go-swagger; DO NOT EDIT.

package blog

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// ListAllPostsHandlerFunc turns a function with the right signature into a list all posts handler
type ListAllPostsHandlerFunc func(ListAllPostsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ListAllPostsHandlerFunc) Handle(params ListAllPostsParams) middleware.Responder {
	return fn(params)
}

// ListAllPostsHandler interface for that can handle valid list all posts params
type ListAllPostsHandler interface {
	Handle(ListAllPostsParams) middleware.Responder
}

// NewListAllPosts creates a new http.Handler for the list all posts operation
func NewListAllPosts(ctx *middleware.Context, handler ListAllPostsHandler) *ListAllPosts {
	return &ListAllPosts{Context: ctx, Handler: handler}
}

/*ListAllPosts swagger:route GET /admin/posts blog listAllPosts

list all posts by pages

*/
type ListAllPosts struct {
	Context *middleware.Context
	Handler ListAllPostsHandler
}

func (o *ListAllPosts) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewListAllPostsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
