global:
  listen_port: 4000
  admin_jwt_secret: secret  
  admin_key_file: /app/storage/admin_key.txt
database:
  type: mysql
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  host: db
  port: 3306
  name: ${DB_DATABASE}
  options:
    parseTime: 'true'
    charset: 'utf8'